atcn/config/routes.rb
Rails.application.routes.draw do

  get "bills", to: "billings#index", as: "home"
  post "billings", to: "billings#create"
  get "billings/new", to: "billings#new", as: "thalavali"
  get "billings/:id/edit", to: "billings#edit"
  get "billings/(:id)", to: "billings#index", as: "billshow"
  put "billings/:id", to: "billings#update"
  patch "billings/:id", to: "billings#update"
  delete "billings/:id", to: "billings#destroy", as: "big_show"
  resources :customers do
    get "/steeck", to: "customers#steeck", on: :collection
  end
  concern :product do
    resources :products
  end
  resources :companies, concerns: :product
  resources :users
  root to: "users#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

atcn/app/models/billing.rb
class Billing < ApplicationRecord
end

atcn/app/controllers/billings_controller.rb
class BillingsController < ApplicationController
  before_action :set_billing, only: %i[ show edit update destroy ]

  # GET /billings or /billings.json
  def index
    @billings = Billing.all
  end

  # GET /billings/1 or /billings/1.json
  def show
  end

  # GET /billings/new
  def new
    @billing = Billing.new
  end

  # GET /billings/1/edit
  def edit
  end

  # POST /billings or /billings.json
  def create
    @billing = Billing.new(billing_params)

    respond_to do |format|
      if @billing.save
        format.html { redirect_to @billing, notice: "Billing was successfully created." }
        format.json { render :show, status: :created, location: @billing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @billing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /billings/1 or /billings/1.json
  def update
    respond_to do |format|
      if @billing.update(billing_params)
        format.html { redirect_to @billing, notice: "Billing was successfully updated." }
        format.json { render :show, status: :ok, location: @billing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @billing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /billings/1 or /billings/1.json
  def destroy
    @billing.destroy
    respond_to do |format|
      format.html { redirect_to billings_url, notice: "Billing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_billing
      @billing = Billing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def billing_params
      params.fetch(:billing, {})
    end
end

atcn/app/helpers/billings_helper.rb
module BillingsHelper
end

atcn/app/views/billings/_form.html.erb
<%= form_with(model: billing) do |form| %>
  <% if billing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(billing.errors.count, "error") %> prohibited this billing from being saved:</h2>

      <ul>
        <% billing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

atcn/app/views/billings/edit.html.erb
<h1>Editing Billing</h1>

<%= render 'form', billing: @billing %>

<%= link_to 'Show', @billing %> |
<%= link_to 'Back', billings_path %>

atcn/app/views/billings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Billings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @billings.each do |billing| %>
      <tr>
        <td><%= link_to 'Show', billshow %></td>
        <td><%= link_to 'Edit', edit_billing_path(billing) %></td>
        <td><%= link_to 'Destroy', big_show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Billing', thalavali_path %>

atcn/app/views/billings/new.html.erb
<h1>New Billing</h1>

<%= render 'form', billing: @billing %>

<%= link_to 'Back', billings_path %>

atcn/app/views/billings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_billing_path(@billing) %> |
<%= link_to 'Back', billings_path %>